import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import navbarConfig from "@/data/navbarConfig";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <Navbar navConfig={navbarConfig} />
        <main className="relative top-14 min-h-screen px-5 py-5">
          {children}
        </main>
      </body>
    </html>
  );
}
